name: Build , Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-execute-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependances
      run: npm install
    - name: Execute all unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo 'stefan_r'

  execute-UI-tests:
    needs: build-and-execute-unit-tests 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependances
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Start application
      run: npm run start &
    - name: Execute all UI tests
      run: npm run test:ui

  deploy:
    needs: build-and-execute-unit-tests 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_KEY }}
          api-key: ${{ secrets.RENDER_API_KEY }}